// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ALLOCATERESPONSE_H_
#define FLATBUFFERS_GENERATED_ALLOCATERESPONSE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct RemoteBlock;

struct RdmaAllocateResponse;
struct RdmaAllocateResponseBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) RemoteBlock FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t rkey_;
  int32_t padding0__;
  uint64_t remote_addr_;

 public:
  RemoteBlock()
      : rkey_(0),
        padding0__(0),
        remote_addr_(0) {
    (void)padding0__;
  }
  RemoteBlock(uint32_t _rkey, uint64_t _remote_addr)
      : rkey_(::flatbuffers::EndianScalar(_rkey)),
        padding0__(0),
        remote_addr_(::flatbuffers::EndianScalar(_remote_addr)) {
    (void)padding0__;
  }
  uint32_t rkey() const {
    return ::flatbuffers::EndianScalar(rkey_);
  }
  uint64_t remote_addr() const {
    return ::flatbuffers::EndianScalar(remote_addr_);
  }
};
FLATBUFFERS_STRUCT_END(RemoteBlock, 16);

struct RdmaAllocateResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RdmaAllocateResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BLOCKS = 4,
    VT_ERROR_CODE = 6
  };
  const ::flatbuffers::Vector<const RemoteBlock *> *blocks() const {
    return GetPointer<const ::flatbuffers::Vector<const RemoteBlock *> *>(VT_BLOCKS);
  }
  uint32_t error_code() const {
    return GetField<uint32_t>(VT_ERROR_CODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BLOCKS) &&
           verifier.VerifyVector(blocks()) &&
           VerifyField<uint32_t>(verifier, VT_ERROR_CODE, 4) &&
           verifier.EndTable();
  }
};

struct RdmaAllocateResponseBuilder {
  typedef RdmaAllocateResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_blocks(::flatbuffers::Offset<::flatbuffers::Vector<const RemoteBlock *>> blocks) {
    fbb_.AddOffset(RdmaAllocateResponse::VT_BLOCKS, blocks);
  }
  void add_error_code(uint32_t error_code) {
    fbb_.AddElement<uint32_t>(RdmaAllocateResponse::VT_ERROR_CODE, error_code, 0);
  }
  explicit RdmaAllocateResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RdmaAllocateResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RdmaAllocateResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RdmaAllocateResponse> CreateRdmaAllocateResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const RemoteBlock *>> blocks = 0,
    uint32_t error_code = 0) {
  RdmaAllocateResponseBuilder builder_(_fbb);
  builder_.add_error_code(error_code);
  builder_.add_blocks(blocks);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RdmaAllocateResponse> CreateRdmaAllocateResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<RemoteBlock> *blocks = nullptr,
    uint32_t error_code = 0) {
  auto blocks__ = blocks ? _fbb.CreateVectorOfStructs<RemoteBlock>(*blocks) : 0;
  return CreateRdmaAllocateResponse(
      _fbb,
      blocks__,
      error_code);
}

inline const RdmaAllocateResponse *GetRdmaAllocateResponse(const void *buf) {
  return ::flatbuffers::GetRoot<RdmaAllocateResponse>(buf);
}

inline const RdmaAllocateResponse *GetSizePrefixedRdmaAllocateResponse(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<RdmaAllocateResponse>(buf);
}

inline bool VerifyRdmaAllocateResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<RdmaAllocateResponse>(nullptr);
}

inline bool VerifySizePrefixedRdmaAllocateResponseBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<RdmaAllocateResponse>(nullptr);
}

inline void FinishRdmaAllocateResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<RdmaAllocateResponse> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRdmaAllocateResponseBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<RdmaAllocateResponse> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_ALLOCATERESPONSE_H_
