repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    - id: yapf
      args: ['--parallel', '--in-place']
      files: \.(py)$
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        files: \.(c|cc|cxx|cpp|cu|h|hpp)$
